require("lazy").setup({
  require("plugins.snacks"),
  require("plugins.blueberry"),
  require("plugins.noice"),
  require("plugins.treesitter"),
  require("plugins.lsp"),
  require("plugins.nvim-tree"),
  require("plugins.devicons"),
  require("plugins.nonicons"),
  require("plugins.lualine"),
  require("plugins.autopairs"),
  require("plugins.cmp"),
  require("plugins.wakatime"),
  require("plugins.telescope"),
  require("plugins.oil"),
  require("plugins.presence"),
  require("plugins.rustaceanvim"),
  require("plugins.fidget")
})

